services:
  manager:
    build:
      context: ./backend
      dockerfile: manager/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - ANTHROPIC_API_KEY=${CLAUDE_KEY}

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5500:80"
    depends_on:
      - manager